### ISSUE TITLE
This Artchitecture in Nuxt3 or Nuxt2 TS

### ISSUE THREAD

**Issue by rodolfo-santos** [areindl/nuxt-structure-with-modules#2]
Do you recommend some example repository using this architecture, but in nuxt3 or nuxt2 with typescript

**Comment by Baroshem** [comment]
@rodolfo-santos I am currently writing an article about Domain Driven Design in Nuxt 3 with Pinia. I will link it here when it will go live :)

**Comment by Baroshem** [comment]
@rodolfo-santos 

https://dev.to/theandrewsky/using-modules-and-pinia-to-structure-nuxt-3-app-5963

**Comment by areindl** [comment]
@rodolfo-santos we use this structure heavily at @mindfuel, but our repo is private. We have 6 modules which stores each and it works really well.

For Nuxt 3 things have changed a bit. I haven't tried it with Nuxt 3 yet.

@Baroshem: thanks! nice article. Are you already on Nuxt 3 at Vue Storefront?

**Comment by areindl** [comment]
Hi @Baroshem and @rodolfo-santos  I added a new branch and implemented a Nuxt 3 Version.

Link: https://github.com/areindl/nuxt-structure-with-modules/tree/nuxt3

**Comment by rodrigoodev** [comment]
god

**Comment by rodolfo-santos** [comment]
I created a [nuxt2 example](https://github.com/rodolfo-santos/nuxt2-typescript-with-modules) adding typescript and [nuxt-property-decorator](https://github.com/nuxt-community/nuxt-property-decorator)

I'll leave the [link here](https://github.com/rodolfo-santos/nuxt2-typescript-with-modules) in case anyone wants to collaborate
