### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by areindl** [areindl/nuxt-structure-with-modules#4]
I have added a new branch that shows how this Domain-Driven-Design inspired structure can be implemented in Nuxt 3:

https://github.com/areindl/nuxt-structure-with-modules/tree/nuxt3

Feedback appreciated 👍

**Comment by rodolfo-santos** [comment]
Very well! But registering the store module in asyncData is not working well, when reloading the /booking page, gives errors

![image](https://user-images.githubusercontent.com/29019771/165376695-5746f31f-c444-4924-9e24-2a37ffb6b091.png)

**Comment by areindl** [comment]
I have upgraded the repo to Nuxt 3 and it's now using Nuxt 3.9. 

I am happy to get some feedback @rodolfo-santos
