### ISSUE TITLE
Nuxt 3 help

### ISSUE THREAD

**Issue by mitraecp** [areindl/nuxt-structure-with-modules#5]
Great tutorial, and maybe the only one on the web. I'm studying DDD and looking for how to apply it with Nuxt 3. I still have many doubts, but here's one of them...

* if I want to use global things, for example a  validator.js, to check fields in a form, and reuse it in several modules, in which folder would I put it?

**Comment by BaptisteCrouzetPerformancePME** [comment]
I am interested too by the response 🙂

**Comment by rodolfo-santos** [comment]
I always use a structure similiar to this one.

![image](https://user-images.githubusercontent.com/29019771/182487357-33334db6-da81-439c-a934-d4a47c6a8145.png)

**Comment by areindl** [comment]
Thanks everyone! I will try to update the branch soon.

It's currently still on Nuxt 3 RC3 and quite a bit changed: https://github.com/areindl/nuxt-structure-with-modules/tree/nuxt3

**Comment by areindl** [comment]
Hi all! The branch is now updated to Nuxt 3.3.3 and it is working. I will do a PR and update the repo.

https://github.com/areindl/nuxt-structure-with-modules/pull/6
